import type { Appearance, SemanticColorTheme } from '../semantic-colors';
import { primitiveColors } from './primitive-colors';

/** Private palette resolution. Public consumers receive semantic CSS variables. */
export const semanticColorThemes = {
  light: {
    'surface-page': primitiveColors.neutral[100],
    'surface-panel': primitiveColors.neutral[50],
    'surface-raised': primitiveColors.neutral[50],
    'text-primary': primitiveColors.neutral[900],
    'text-muted': primitiveColors.neutral[600],
    'text-on-accent': primitiveColors.neutral[50],
    'text-on-success': primitiveColors.neutral[50],
    'text-on-warning': primitiveColors.neutral[50],
    'text-on-danger': primitiveColors.neutral[50],
    'text-on-info': primitiveColors.neutral[50],
    'border-default': primitiveColors.neutral[300],
    'status-success': primitiveColors.green[700],
    'status-warning': primitiveColors.amber[800],
    'status-danger': primitiveColors.red[700],
    'status-info': primitiveColors.cyan[700],
    'accent-primary': primitiveColors.blue[700],
    'ai-draft-surface': primitiveColors.amber[100],
    'ai-draft-text': primitiveColors.amber[900],
    'ai-draft-border': primitiveColors.amber[400],
    'ai-draft-accent': primitiveColors.amber[700],
    'ai-approved-surface': primitiveColors.green[100],
    'ai-approved-text': primitiveColors.green[900],
    'ai-approved-border': primitiveColors.green[400],
    'ai-approved-accent': primitiveColors.green[700],
  },
  dark: {
    'surface-page': primitiveColors.neutral[950],
    'surface-panel': primitiveColors.neutral[900],
    'surface-raised': primitiveColors.neutral[800],
    'text-primary': primitiveColors.neutral[50],
    'text-muted': primitiveColors.neutral[400],
    'text-on-accent': primitiveColors.neutral[950],
    'text-on-success': primitiveColors.neutral[950],
    'text-on-warning': primitiveColors.neutral[950],
    'text-on-danger': primitiveColors.neutral[950],
    'text-on-info': primitiveColors.neutral[950],
    'border-default': primitiveColors.neutral[700],
    'status-success': primitiveColors.green[400],
    'status-warning': primitiveColors.amber[300],
    'status-danger': primitiveColors.red[400],
    'status-info': primitiveColors.cyan[300],
    'accent-primary': primitiveColors.blue[400],
    'ai-draft-surface': primitiveColors.amber[950],
    'ai-draft-text': primitiveColors.amber[100],
    'ai-draft-border': primitiveColors.amber[700],
    'ai-draft-accent': primitiveColors.amber[300],
    'ai-approved-surface': primitiveColors.green[950],
    'ai-approved-text': primitiveColors.green[100],
    'ai-approved-border': primitiveColors.green[700],
    'ai-approved-accent': primitiveColors.green[300],
  },
} as const satisfies Record<Appearance, SemanticColorTheme>;
